### ISSUE TITLE
Attention Map Generation

### ISSUE THREAD

**Issue by tnwls6865** [kahnchana/clippy#1]
Thanks for the release of clippy model!
I was wondering if it is possible to show attention maps of input images using released clippy-B-16 model？

**Comment by kahnchana** [comment]
Thanks a lot for your interest in our work. 

Can you elaborate your question? Do you mean the attention map of a given spatial point to all other points? CLIPpy does not contain a CLS token, so attention operations occur only between image tokens.

**Comment by tnwls6865** [comment]
Yes, I want to get the attention map of each block between image tokens.

**Comment by kahnchana** [comment]
I've added a modified notebook [here](https://colab.research.google.com/drive/1dpgaoLjUGAdsGUP3poWZSuoK-zU5eoxU?usp=sharing) that can extract attention maps. 

I will try to update the main repo with this later too. Hope this helps!

**Comment by tnwls6865** [comment]
Thank You !!
